config/routes.rb
Rails.application.routes.draw do

	mount LetsencryptPlugin::Engine, at: '/'

	begin
		ActiveAdmin.routes(self)
	rescue Exception => e
		puts "ActiveAdmin: #{e.class}: #{e}"
	end

	devise_for :admin_users, ActiveAdmin::Devise.config

	devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }


	root 'home#index'

	resources :categories
	get '/destacados' => 'categories#featured', :as => :featured

	resources :products do
		get 'checkout', to: 'products#purchase'
	end

	#get '/cotizador' => 'home#cotizador'

	get '/me' => 'users#profile', :as => :profile


	post '/contact_email' => 'api/v1/users#contact_email'
	post '/add_to_newsletter' => 'api/v1/users#add_to_newsletter', :as => :add_to_newsletter

	get '/tracking/:tracking_code' => 'orders#tracking', :as => :tracking_order_by_code

	# Checkout
	get '/checkout' => 'checkout#show', :as => :checkout
	get 'single-checkout-success', to: 'checkout#single_checkout_success'
	get 'single-checkout-pending', to: 'checkout#single_checkout_pending'
	get 'single-checkout-cancelled', to: 'checkout#single_checkout_cancelled'

	get 'cart-checkout-success', to: 'checkout#cart_checkout_success'
	get 'cart-checkout-pending', to: 'checkout#cart_checkout_pending'
	get 'cart-checkout-cancelled', to: 'checkout#cart_checkout_cancelled'

	# API
	scope module: 'api' do
		scope '1', module: 'v1' do
			get 'user/favourites' => 'favourites#index'

			# Cart
			get 'user/products_in_cart', to: 'cart#get_products_in_cart', :as => :product_in_cart
			post 'user/checkout/:product_id', to: 'cart#add_product_to_cart', :as => :add_product_to_cart
			put 'user/checkout_row/:product_row_id', to: 'cart#edit_checkout_product_row', :as => :edit_checkout_row
			delete 'user/cart/:product_id', to: 'cart#remove_cart_product_row', :as => :remove_cart_product_row

			# Favourites
			post 'user/favourites/:product_id', to: 'favourites#create', :as => :add_product_to_favourites
			delete 'user/favourites/:product_id', to: 'favourites#destroy', :as => :remove_product_from_favourites

			post '/chat_response' => 'chat#dialog_flow_response'
		end
	end

	# error pages
	%w( 404 422 500 503 ).each do |code|
		get code, :to => 'errors#show', :code => code
	end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)      default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  password_salt          :string(32)
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  deleted_at             :datetime
#
# Indexes
#
#  index_users_on_deleted_at            (deleted_at)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord

	acts_as_paranoid

	devise :database_authenticatable, :registerable, :encryptable,
		:recoverable, :rememberable, :trackable, :validatable,
		:omniauthable, :confirmable, :omniauth_providers => [:facebook]

	validates :email, presence: true, allow_blank: false,
		:uniqueness => { :case_sensitive => false }, length: { maximum: 255 }

	after_create :create_checkout_list

	has_one :checkout_list, :dependent => :destroy
	has_one :purchased_list, :dependent => :destroy
	has_many :orders, :dependent => :destroy
	has_many :favourites, :dependent => :destroy

	def create_checkout_list
		CheckoutList.create(:user => self)
	end

	def self.find_for_facebook_oauth(access_token, signed_in_resource = nil)
		data = access_token.extra.raw_info
		if user = User.where(:email => data.email).first
			user
		else # Create a user with a stub password.
			user = User.new(:email => data.email, :password => Devise.friendly_token[0, 20])
			user.skip_confirmation!
			user.save!
			user
		end
	end

	def name
		email.gsub(/.+@([^.]+).+/, '\0');
	end

	def current_orders
		Order.current.of(self).desc
	end

	def add_product_to_cart product, quantity = 1
		self.checkout_list = CheckoutList.create(:user => self) unless self.checkout_list.present?
		self.checkout_list.save_product_row product, quantity
		self.save!
	end

	def has_product_in_cart? product
		checkout_list.present? and checkout_list.product_rows.present? and checkout_list.product_rows.where(:product => product).exists?
	end

	def has_product_as_favourite? product
		Favourite.exists?(product: product, user: self)
	end

	def has_bought? product
		purchased_list.present? and purchased_list.product_rows.present? and purchased_list.product_rows.where(:product => product).exists?
	end

	def cart_count
		checkout_list.present? ? checkout_list.product_rows.count : 0
	end

end

app/controllers/api/v1/cart_controller.rb
class Api::V1::CartController < Api::V1::ApiController

	before_action :set_product, only: [:add_product_to_cart, :remove_cart_product_row]
	before_action :set_product_row, only: [:edit_checkout_product_row]
	before_action :set_quantity, only: [:edit_checkout_product_row, :add_product_to_cart]

	def get_products_in_cart
		render_successful_response(
			current_user.checkout_list.product_rows,
			ProductRowSerializer
		)
	end

	def add_product_to_cart
		AddProductToCart.with(user: current_user, product: @product, quantity: @quantity)
		render json: { :response => 'success' }
	end

	def edit_checkout_product_row
		if @quantity.present?
			@product_row.update_attribute(:quantity, @quantity)
			render json: { :response => 'success' }
		end
	end

	def remove_cart_product_row
		current_user.checkout_list.product_rows.find_by(:product => params[:product_id]).destroy
		render json: { :response => 'success' }
	end

	private
	def set_product
		@product = Product.friendly.find(params[:product_id])
	end

	def set_product_row
		@product_row = ProductRow.find(params[:product_row_id])
	end

	def set_quantity
		@quantity = params[:quantity].present? ? params[:quantity] : 1
	end


end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
	before_action :authenticate_user!, except: [:contact_email, :add_to_newsletter]
	protect_from_forgery with: :exception
	invisible_captcha only: [:contact_email]

	def contact_email
		if params['authenticity_token'].present?
			AdminMailer.contact_email(contact_params).deliver_now
			flash[:notice] = 'Se envió el mensaje, en breve nos vamos a estar contactando. Gracias!'
			redirect_to root_path
		else
			raise Exception
		end
	end

	def add_to_newsletter
		begin
			MailChimpApi.add_member email: params[:email] unless params[:email].nil?
			render_successful_empty_response
		rescue StandardError => ex
			response = Hash.new
			response[:status] = 'failed'
			response[:message] = ex.title == 'Member Exists' ? 'El usuario ya esta registrado' : 'El email no es válido'
			render_response_message hash: response, status: 200
		end
	end

	private

	def contact_params
		params.permit(:lazlo_name, :lazlo_email, :lazlo_message, :authenticity_token)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper

	before_action :authenticate_user!

	def profile
		@statuses = Order.cart_order_statuses
	end

end

app/views/users/cart/_product_cart_row.html.erb
<div class="cart-product-row"
     data-remove-path="<%= remove_cart_product_row_url product_hash(@product_row.product.id) %>"
     data-put-path="<%= edit_checkout_row_url product_row_hash(@product_row.id) %>">

  <div class="cart-product-row-header">
    <a href="<%= product_path @product_row.product %>" class="smooth-transition">
      <%= @product_row.product.name %>
    </a>
    <i class="fa fa-trash-o remove-row" aria-hidden="true"></i>
  </div>

  <div class="left-block">
    <a class="cart-product-image" href="<%= product_path @product_row.product %>">
      <img src="<%= @product_row.product.image.url(:thumb) %>"/>
    </a>
  </div>


  <div class="right-block">

    <!-- <div class="product-detail-row">
      <strong>Medidas:</strong>
      <span>90x60x45cm</span>
    </div>
    -->
    <div class="product-detail-row">
      <strong>Cantidad:</strong>
      <span>
        <i class="fa fa-minus-circle" aria-hidden="true"></i>
        <b class="quantity-message"><%= @product_row.quantity %></b>
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
      </span>
    </div>

    <div class="product-detail-row">
      <strong>Precio:</strong>
      <span class="cart-product-price" data-product-price="<%= @product_row.product.price.to_i %>">
        <%= format_price @product_row.total %>
      </span>
    </div>

  </div>

</div>

app/views/users/cart/_sidebar_cart.html.erb
<aside class="sidebar hide-on-shadow-click" data-prudcts-url="<%= product_in_cart_url %>">

  <i class="fa fa-times close-sidebar" aria-hidden="true"></i>

  <div class="inner-sidebar" data-simplebar>
    <% has_products = (user_signed_in? and current_user.checkout_list.present? and current_user.checkout_list.product_rows.any?) %>

    <div class="user-cart-left-block user-cart-block <%= has_products ? 'display-with-products' : '' %>"
      >
      <% if has_products %>
        <% current_user.checkout_list.product_rows.each do |product_row|
          @product_row = product_row
    %>
          <!-- Start Product Cart Row -->
          <%= render :partial => 'users/cart/product_cart_row' %>
          <!-- End Product Cart Row -->
        <% end %>
      <% end %>
    </div>

    <div class="user-cart-right-block user-cart-block <%= has_products ? 'display-with-products' : '' %>">
      <h2>Total:</h2>
      <h3 class="total-sum"></h3>
      <a href="<%= checkout_path %>" class="checkout-button smooth-transition  yellow-with-icon-hover button">
        <span>CHECKOUT</span>
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
      </a>
    </div>

    <div class="no-products-message cart-no-products-message <%= has_products ? '' : 'display-when-empty' %>">
      <h5>Todavía no tenés ningun producto en el carrito</h5>
    </div>

  </div>
</aside>