config/routes.rb
Rails.application.routes.draw do

	mount LetsencryptPlugin::Engine, at: '/'

	begin
		ActiveAdmin.routes(self)
	rescue Exception => e
		puts "ActiveAdmin: #{e.class}: #{e}"
	end

	devise_for :admin_users, ActiveAdmin::Devise.config

	devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }


	root 'home#index'

	resources :categories
	get '/destacados' => 'categories#featured', :as => :featured

	resources :products do
		get 'checkout', to: 'products#purchase'
	end

	#get '/cotizador' => 'home#cotizador'

	get '/me' => 'users#profile', :as => :profile


	post '/contact_email' => 'api/v1/users#contact_email'
	post '/add_to_newsletter' => 'api/v1/users#add_to_newsletter', :as => :add_to_newsletter

	get '/tracking/:tracking_code' => 'orders#tracking', :as => :tracking_order_by_code

	# Checkout
	get '/checkout' => 'checkout#show', :as => :checkout
	get 'single-checkout-success', to: 'checkout#single_checkout_success'
	get 'single-checkout-pending', to: 'checkout#single_checkout_pending'
	get 'single-checkout-cancelled', to: 'checkout#single_checkout_cancelled'

	get 'cart-checkout-success', to: 'checkout#cart_checkout_success'
	get 'cart-checkout-pending', to: 'checkout#cart_checkout_pending'
	get 'cart-checkout-cancelled', to: 'checkout#cart_checkout_cancelled'

	# API
	scope module: 'api' do
		scope '1', module: 'v1' do
			get 'user/favourites' => 'favourites#index'

			# Cart
			get 'user/products_in_cart', to: 'cart#get_products_in_cart', :as => :product_in_cart
			post 'user/checkout/:product_id', to: 'cart#add_product_to_cart', :as => :add_product_to_cart
			put 'user/checkout_row/:product_row_id', to: 'cart#edit_checkout_product_row', :as => :edit_checkout_row
			delete 'user/cart/:product_id', to: 'cart#remove_cart_product_row', :as => :remove_cart_product_row

			# Favourites
			post 'user/favourites/:product_id', to: 'favourites#create', :as => :add_product_to_favourites
			delete 'user/favourites/:product_id', to: 'favourites#destroy', :as => :remove_product_from_favourites

			post '/chat_response' => 'chat#dialog_flow_response'
		end
	end

	# error pages
	%w( 404 422 500 503 ).each do |code|
		get code, :to => 'errors#show', :code => code
	end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)      default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  password_salt          :string(32)
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  deleted_at             :datetime
#
# Indexes
#
#  index_users_on_deleted_at            (deleted_at)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord

	acts_as_paranoid

	devise :database_authenticatable, :registerable, :encryptable,
		:recoverable, :rememberable, :trackable, :validatable,
		:omniauthable, :confirmable, :omniauth_providers => [:facebook]

	validates :email, presence: true, allow_blank: false,
		:uniqueness => { :case_sensitive => false }, length: { maximum: 255 }

	after_create :create_checkout_list

	has_one :checkout_list, :dependent => :destroy
	has_one :purchased_list, :dependent => :destroy
	has_many :orders, :dependent => :destroy
	has_many :favourites, :dependent => :destroy

	def create_checkout_list
		CheckoutList.create(:user => self)
	end

	def self.find_for_facebook_oauth(access_token, signed_in_resource = nil)
		data = access_token.extra.raw_info
		if user = User.where(:email => data.email).first
			user
		else # Create a user with a stub password.
			user = User.new(:email => data.email, :password => Devise.friendly_token[0, 20])
			user.skip_confirmation!
			user.save!
			user
		end
	end

	def name
		email.gsub(/.+@([^.]+).+/, '\0');
	end

	def current_orders
		Order.current.of(self).desc
	end

	def add_product_to_cart product, quantity = 1
		self.checkout_list = CheckoutList.create(:user => self) unless self.checkout_list.present?
		self.checkout_list.save_product_row product, quantity
		self.save!
	end

	def has_product_in_cart? product
		checkout_list.present? and checkout_list.product_rows.present? and checkout_list.product_rows.where(:product => product).exists?
	end

	def has_product_as_favourite? product
		Favourite.exists?(product: product, user: self)
	end

	def has_bought? product
		purchased_list.present? and purchased_list.product_rows.present? and purchased_list.product_rows.where(:product => product).exists?
	end

	def cart_count
		checkout_list.present? ? checkout_list.product_rows.count : 0
	end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
	before_action :authenticate_user!, except: [:contact_email, :add_to_newsletter]
	protect_from_forgery with: :exception
	invisible_captcha only: [:contact_email]

	def contact_email
		if params['authenticity_token'].present?
			AdminMailer.contact_email(contact_params).deliver_now
			flash[:notice] = 'Se envió el mensaje, en breve nos vamos a estar contactando. Gracias!'
			redirect_to root_path
		else
			raise Exception
		end
	end

	def add_to_newsletter
		begin
			MailChimpApi.add_member email: params[:email] unless params[:email].nil?
			render_successful_empty_response
		rescue StandardError => ex
			response = Hash.new
			response[:status] = 'failed'
			response[:message] = ex.title == 'Member Exists' ? 'El usuario ya esta registrado' : 'El email no es válido'
			render_response_message hash: response, status: 200
		end
	end

	private

	def contact_params
		params.permit(:lazlo_name, :lazlo_email, :lazlo_message, :authenticity_token)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper

	before_action :authenticate_user!

	def profile
		@statuses = Order.cart_order_statuses
	end

end

app/views/users/_profile_detail.html.erb
<section class="profile-detail">
  <div class="grilla user-purchased-products profile-container">
    <h6>TU CUENTA</h6>

    <div class="block block-left">
      <span><%= current_user.name %></span>
      <%= link_to 'cerrar sesión', destroy_user_session_path, :method => :delete, :class => 'log-out-button' %>

      <p>No hay cuenta de mercado pago vinculada</p>
      <!-- <a href="">vincular</a> -->

      <div class="profile-promotion">
        <h4>APROVECHÁ DEL CUPÓN</h4>
        <h3>DE $200</h3>
      </div>
    </div>


    <div class="block block-right">

      <div class="profile-products-slider-buttons"></div>

      <div class="bx-wrapper profile-products-slider">

        <!-- Start Profile Detail Favourites -->
        <%= render :partial => 'users/profile_detail_favourites' %>
        <!-- End Profile Detail Favourites -->


        <!-- Start Profile Detail Cart -->
        <%= render :partial => 'users/profile_detail_cart' %>
        <!-- End Profile Detail Cart -->

        <!-- Start Profile Detail History -->
        <%= render :partial => 'users/profile_detail_history' %>
        <!-- End Profile Detail History -->

      </div>

    </div>

  </div>

</section>

app/views/users/_profile_detail_cart.html.erb
<div class="profile-products-block">
  <div class="profile-products-inner-block">
    <% if current_user.checkout_list.present? and current_user.checkout_list.product_rows.any? %>
      <div class="user-cart-left-block user-cart-block">
        <% current_user.checkout_list.product_rows.each do |product_row|
          @product_row = product_row
         %>
          <!-- Start Product Cart Row -->
          <%= render :partial => 'users/cart/product_cart_row' %>
          <!-- End Product Cart Row -->
        <% end %>
      </div>

      <div class="user-cart-right-block user-cart-block">
        <h2>Total</h2>
        <h3 class="total-sum"></h3>
        <a href="<%= checkout_path %>" class="checkout-button smooth-transition  yellow-with-icon-hover button">
          <span>CHECKOUT</span>
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        </a>
      </div>

    <% end %>

    <div class="no-products-message cart-no-products-message">
      <h5>Todavía no tenés ningun producto en el carrito</h5>
    </div>

  </div>
</div>

app/views/users/_profile_detail_favourites.html.erb
<div class="profile-products-block">
  <div class="profile-products-inner-block">
    <% if current_user.favourites.any? %>
      <% current_user.favourites.each_with_index do |favourite, i| %>
        <a class="image-block favourite-product-block <%= i % 3 == 0 ? 'last' : '' %>"
           href="<%= product_path favourite.product %>">
          <div class="image-block-with-transition no-image-translate hover-block-trigger without-margin">

            <%= render :partial => 'icons/eye_icon' %>

            <%= image_tag favourite.product.image.url(:rectangular5) %>

            <div class="product-description">
              <h5><%= format_price favourite.product.price %>
                <strong><%= favourite.product.name %></strong>
              </h5>
              <!-- <h6>medidas: 50x50x70 de alto</h6> -->
            </div>


          </div>
        </a>
      <% end %>
    <% else %>
      <div class="no-products-message">
        <h5>Todavía no marcaste ningún producto como favorito
          <a class="product-action-button with-hover">
            <%= render :partial => 'icons/like_button' %>
          </a>
        </h5>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_profile_detail_history.html.erb
<div class="profile-products-block">
  <div class="profile-products-inner-block">
    <% if current_user.orders.delivered.any? %>
      <% current_user.orders.delivered.order(:created_at => 'DESC').each do |order|
        @order = order   %>
        <%= render :partial => 'users/orders/profile_order_row' %>
      <% end %>
    <% else %>
      <div class="no-products-message">
        <h5>Todavía no realizaste o finalizaste ninguna compra</h5>
      </div>
    <% end %>
  </div>
</div>

app/views/users/cart.html.erb
<!-- Start Header -->
<%= render :partial => 'layouts/header' %>
<!-- End Header -->



<div class="grilla user-cart">

  <h3>FAVORITOS</h3>


  <% if @user_products_list.present? %>
      <% @user_products_list.product_rows.each do |product_row|
        remove_path_hash = {:user_id => current_user.id,
                            :product_id => product_row.product.id,
                            :version => Rails.application.config.API_VERSION}
      %>
          <div class="cart-product-row" data-remove-path="<%= remove_cart_product_path(remove_path_hash) %>">

            <i class="fa fa-times smooth-transition" aria-hidden="true"></i>

            <div class="cart-product-image">
              <img src="<%= product_row.product.image.url(:thumb) %>"/>
            </div>

            <h2>
              <a href="<%= product_path product_row.product %>" class="smooth-transition"><%= product_row.product.name %></a>
            </h2>

            <span class="cart-product-price">
              <%= format_price product_row.product.price %>
            </span>
          </div>
      <% end %>
  <% else %>
      <h2>No tiene productos en tu lista</h2>
  <% end %>
</div>



<!-- Start Footer -->
<%= render :partial => 'layouts/footer' %>
<!-- End Footer -->

app/views/users/profile.erb
<!-- Start Header -->
<%= render :partial => 'layouts/header' %>
<!-- End Header -->

<% if current_user.current_orders.any? %>

  <div class="profile-purchase-header">

    <div class="grilla">

      <div class="purchase-block">
        <h2>tu compra</h2>
      </div>

      <% current_user.current_orders.each do |order|
        @order = order  %>
        <%= render :partial => 'users/orders/order_tracking' %>
      <% end %>

    </div>
  </div>
<% end %>


<!-- Start Profile Detail -->
<%= render :partial => 'users/profile_detail' %>
<!-- End Profile Detail -->


<!-- Start Footer -->
<%= render :partial => 'layouts/footer' %>
<!-- End Footer -->