config/routes.rb
Rails.application.routes.draw do

	mount LetsencryptPlugin::Engine, at: '/'

	begin
		ActiveAdmin.routes(self)
	rescue Exception => e
		puts "ActiveAdmin: #{e.class}: #{e}"
	end

	devise_for :admin_users, ActiveAdmin::Devise.config

	devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }


	root 'home#index'

	resources :categories
	get '/destacados' => 'categories#featured', :as => :featured

	resources :products do
		get 'checkout', to: 'products#purchase'
	end

	#get '/cotizador' => 'home#cotizador'

	get '/me' => 'users#profile', :as => :profile


	post '/contact_email' => 'api/v1/users#contact_email'
	post '/add_to_newsletter' => 'api/v1/users#add_to_newsletter', :as => :add_to_newsletter

	get '/tracking/:tracking_code' => 'orders#tracking', :as => :tracking_order_by_code

	# Checkout
	get '/checkout' => 'checkout#show', :as => :checkout
	get 'single-checkout-success', to: 'checkout#single_checkout_success'
	get 'single-checkout-pending', to: 'checkout#single_checkout_pending'
	get 'single-checkout-cancelled', to: 'checkout#single_checkout_cancelled'

	get 'cart-checkout-success', to: 'checkout#cart_checkout_success'
	get 'cart-checkout-pending', to: 'checkout#cart_checkout_pending'
	get 'cart-checkout-cancelled', to: 'checkout#cart_checkout_cancelled'

	# API
	scope module: 'api' do
		scope '1', module: 'v1' do
			get 'user/favourites' => 'favourites#index'

			# Cart
			get 'user/products_in_cart', to: 'cart#get_products_in_cart', :as => :product_in_cart
			post 'user/checkout/:product_id', to: 'cart#add_product_to_cart', :as => :add_product_to_cart
			put 'user/checkout_row/:product_row_id', to: 'cart#edit_checkout_product_row', :as => :edit_checkout_row
			delete 'user/cart/:product_id', to: 'cart#remove_cart_product_row', :as => :remove_cart_product_row

			# Favourites
			post 'user/favourites/:product_id', to: 'favourites#create', :as => :add_product_to_favourites
			delete 'user/favourites/:product_id', to: 'favourites#destroy', :as => :remove_product_from_favourites

			post '/chat_response' => 'chat#dialog_flow_response'
		end
	end

	# error pages
	%w( 404 422 500 503 ).each do |code|
		get code, :to => 'errors#show', :code => code
	end


end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :text(65535)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  slug               :string(255)
#  category_id        :integer
#  views              :integer          default(0)
#  featured           :boolean          default(FALSE)
#  visible            :boolean          default(TRUE)
#  deleted_at         :datetime
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#  index_products_on_deleted_at   (deleted_at)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

class Product < ApplicationRecord

	acts_as_paranoid

	include Rails.application.routes.url_helpers

	extend FriendlyId
	friendly_id :name, use: :slugged

	belongs_to :category
	has_many :orders, :dependent => :destroy
	has_many :product_images, :dependent => :destroy
	has_many :product_rows, :dependent => :destroy
	has_many :favourites, :dependent => :destroy
	has_many :product_sizes, :dependent => :destroy


	accepts_nested_attributes_for :product_sizes, :allow_destroy => true
	accepts_nested_attributes_for :product_images, :allow_destroy => true


	validates_presence_of :slug, :name
	validates :product_sizes, :length => { :minimum => 1 }
	validates :name, allow_blank: false,
		:uniqueness => { :case_sensitive => false }, length: { maximum: 255 }

	before_save :parse_slug, :if => :name_changed?

	has_attached_file :image,
		styles: {
			big: "800x800#",
			medium: "300x300#",
			rectangular1: "584x288#",
			rectangular2: "544x350#",
			rectangular3: "455x285#",
			rectangular4: "360x350#",
			rectangular5: "360x285#",
			rectangular6: "455x350#",
			thumb: "162x162#"
		},
		default_url: "/images/:style/missing.png", :preserve_files => true
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


	scope :featured, -> { limit(6).order('featured desc, views desc') }

	scope :visible, -> { where(:visible => true) }

	scope :most_viewed, -> {
		order('views DESC').first
	}

	scope :most_liked, -> {
		find(Favourite.group(:product_id).order('count(*) DESC').limit(1).pluck(:product_id).first)
	}

	#Todo Add suggestions logic
	scope :suggestions_for, -> (product) { where(:category => product.category).limit(7) }

	def price
    default_product.present? ? default_product.price : 0
	end

	def size
    default_product.present? ? default_product.name : '0x0cm'
  end

	def image_uri
		URI.join($request.url, self.image.url)
	end

	private
  def default_product
    product_sizes.order('price ASC').first
  end

	def parse_slug
		self.slug = self.name.downcase.strip.gsub(' ', '-').gsub('ñ', 'n').gsub(/[^\w-]/, '')
		self.slug = self.slug + rand(0..9999).to_s if Product.find_by_slug(self.slug).present?
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_request, :set_product, :set_meta_data, :set_product_hash
	before_action :show, :set_section

	def show
		set_purchase_link unless current_user.nil?
		@is_in_cart = (current_user.has_product_in_cart?(@product) ? true : false) unless current_user.nil?
		@is_in_fav = (current_user.has_product_as_favourite?(@product) ? true : false) unless current_user.nil?
	end

	def set_request
		$request = request
	end

	private
	def set_product
		@product = Product.friendly.find(params[:id])
		@suggestions = Product.suggestions_for(@product)
		@product.update_attribute(:views, @product.views + 1)
	end

	def set_meta_data
		set_og_tags @product.name,
			@product.description.squish,
			resource_absolute_path(@product.image.url(:medium))
	end

	def set_purchase_link
		params[:user] = current_user
		params[:product] = @product
		@product_link = MercadoPagoSingleCheckout.(parameters: params, delegate: self).checkout
	end

	def set_product_hash
		@product_hash = {
			:product_id => @product.id,
			:version => Rails.application.config.API_VERSION
		}
	end

	def set_section
		@current_section = 'products'
	end

end

app/helpers/products_helper.rb
module ProductsHelper
	API_VERSION = Rails.application.config.API_VERSION

	def format_price price
		"$" + number_with_delimiter(price.to_i, :delimiter => ".", :separator => ",") unless price.nil?
	end


	def product_hash product_id
		{ :product_id => product_id, :version => API_VERSION }
	end

	def product_row_hash product_row_id
		{ :product_row_id => product_row_id, :version => API_VERSION }
	end

end

app/views/products/_description.html.erb
<h3><%= @product.name %></h3>

<div class="product-detail-container">


  <div class="product-description">

    <div class="text">
      <%= simple_format(@product.description) %>
    </div>
    <!--
    <div class="row">
      <h2>Material:</h2>
      algo algo algo
    </div>

    <div class="row">
      <h2>Color:</h2>
      algo algo algo
    </div>
    -->

    <% if @product.product_sizes.any? %>
      <div class="row">
        <h2>Medidas:</h2>
        <div class="product-select">
          <select name="sizes" id="sizes">
            <% @product.product_sizes.each do |size| %>
              <option value="<%= size.name %>" data-size-price="<%= size.price %>"><%= size.name %></option>
            <% end %>
          </select>

        </div>
      </div>
    <% end %>

    <div class="row">
      <h2>Cantidad:</h2>
      <span class="product-quantity-value">1</span>
      <i class="fa fa-minus-square-o rm-one-product" aria-hidden="true"></i>
      <i class="fa fa-plus-square-o add-one-product" aria-hidden="true"></i>
    </div>

    <div class="row">
      <h2>Precio:</h2>
      <span class="product-price-value" data-product-detail-price="<%= @product.product_sizes.first.price %>">
      <%= format_price @product.product_sizes.first.price %>
      </span>
    </div>


  </div>


  <div class="product-action-buttons">

    <div class="product-action-button-container">

      <a class="product-action-button with-hover <%= user_signed_in? ? 'add-to-fav-btn' : '' %> <%= @is_in_fav ? 'in-fav' : '' %>"
         href="<%= user_signed_in? ? add_product_to_favourites_url(@product_hash) : new_user_session_path %>"
         data-rm-href="<%= remove_product_from_favourites_url(@product_hash) %>">
        <%= render :partial => 'icons/like_button' %>
      </a>

      <span class="count-number fav-count-number">
        <%= Favourite.count_for(@product) %>
      </span>
    </div>

    <!-- Share button -->
    <div class="product-action-button-container"
         onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<%= "#{EmailHelper::URL}/products/#{@product.slug}" %>','facebook-share-dialog','width=626,height=436')">
      <%= render :partial => 'icons/share_button' %>
      <span class="count-number">321</span>
    </div>
    <!-- End Share button -->

  </div>

  <div class="shipping-message">Hacemos envíos a todo el país!</div>

  <% if user_signed_in? %>

    <a class="transparent-with-hover-yellow add-to-cart-btn button <%= @is_in_cart ? 'in-cart' : '' %>"
       href="<%= add_product_to_cart_url(@product_hash) %>"
       data-rm-href="<%= remove_cart_product_row_url(@product_hash) %>">
      <%= @is_in_cart ? 'Guardado en el Carrito!' : 'AGREGAR AL CARRITO' %>
    </a>

  <% else %>
    <a class="transparent-with-hover-yellow button" href="<%= new_user_session_path %>">
      AGREGAR AL CARRITO
    </a>
  <% end %>


  <a href="<%= user_signed_in? ? @product_link : new_user_session_path %>" mp-mode="popup"
     name="MP-Checkout" class="product-buy-button yellow-with-icon-hover button">
    <span>COMPRAR</span>
    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
  </a>



</div>
        

app/views/products/_featured.html.erb
<% if @featured_products.present? %>
    <div class="featured-block">
      <h3 class="section-title">PRODUCTOS DESTACADOS</h3>

      <% @featured_products.each do |featured_product| %>
          <a class="featured-product "
             href="<%= product_path featured_product %>"
             style="background-image: url(<%= featured_product.image.url(:medium) %>);">
            <div class="description smooth-transition">
              <h1><%= featured_product.name %></h1>
              <h4>
                <%= format_price featured_product.price %></h4>
              <span class="see-more">VER MÁS</span>
            </div>
          </a>
      <% end %>

    </div>
<% end %>

app/views/products/_images_detail.html.erb
<% if @product.product_images.present? %>
    <!-- Start image-detail-container -->
    <div class="image-detail-container">
      <img id="product-detail-zoom" src='<%= @product.product_images.first.picture.url(:rectangular1) %>' data-zoom-image="<%= @product.product_images.first.picture.url(:rectangular1) %>"/>
    </div>
    <!-- End image-detail-container -->


    <!-- Start product-images-gallery -->
    <div id="product-images-gallery" class="product-images-gallery">

      <% @product.product_images.each do |image| %>
          <a href="#" data-image="<%= image.picture.url(:rectangular1) %>" data-zoom-image="<%= image.picture.url(:rectangular1) %>">
            <img id="img_01" src="<%= image.picture.url(:rectangular1) %>"/>
          </a>
      <% end %>

    </div>
    <!-- End product-images-gallery -->
<% end %>

app/views/products/_suggestions.html.erb
<% if @suggestions.any? %>
    <div class="suggestions">
      <h3 class="section-title">MIRÁ ESTAS SUGERENCIAS PARA COMBINAR ESTE PRODUCTO</h3>

      <div class="suggestions-container">
        <% @suggestions.each do |suggested_product| %>
            <a class="suggestion-block" href="<%= product_path suggested_product %>">
              <%= image_tag suggested_product.image.url(:thumb) %>
              <h4><%= suggested_product.name %></h4>
              <h4><%= format_price suggested_product.price %></h4>
            </a>
        <% end %>
      </div>
    </div>
<% end %>

app/views/products/show.html.erb
<!-- Start Header -->
<%= render :partial => 'layouts/header' %>
<!-- End Header -->


<div class="grilla margin-top-medium">
  <div class="breadcrumbs">
    <a href="<%= root_path %>">Lazlo</a>
    <span>/</span>
    <a href="<%= category_path @product.category %>"><%= capitalize_first_letters(@product.category.name) %></a>
    <span>/</span>
    <a href="<%= product_path %>" class="active"><%= capitalize_first_letters(@product.name) %></a>
  </div>
</div>

<div class="grilla product-detail-section">

  <div class="products-white-container">
    <div class="inner-container">


      <div class="half-container half-container-left">
        <!-- Start Images Detail -->
        <%= render :partial => 'products/images_detail' %>
        <!-- End Images Detail -->
      </div>

      <div class="half-container half-container-right">
        <!-- Start Description -->
        <%= render :partial => 'products/description' %>
        <!-- End Description -->
      </div>

    </div>
  </div>

  <!-- Start Suggestions -->
  <%= render :partial => 'products/suggestions' %>
  <!-- End suggestions -->

</div>



<script type="text/javascript" src="//resources.mlstatic.com/mptools/render.js"></script>

<!-- Start Footer -->
<%= render :partial => 'layouts/footer' %>
<!-- End Footer -->