config/routes.rb
Rails.application.routes.draw do

	mount LetsencryptPlugin::Engine, at: '/'

	begin
		ActiveAdmin.routes(self)
	rescue Exception => e
		puts "ActiveAdmin: #{e.class}: #{e}"
	end

	devise_for :admin_users, ActiveAdmin::Devise.config

	devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }


	root 'home#index'

	resources :categories
	get '/destacados' => 'categories#featured', :as => :featured

	resources :products do
		get 'checkout', to: 'products#purchase'
	end

	#get '/cotizador' => 'home#cotizador'

	get '/me' => 'users#profile', :as => :profile


	post '/contact_email' => 'api/v1/users#contact_email'
	post '/add_to_newsletter' => 'api/v1/users#add_to_newsletter', :as => :add_to_newsletter

	get '/tracking/:tracking_code' => 'orders#tracking', :as => :tracking_order_by_code

	# Checkout
	get '/checkout' => 'checkout#show', :as => :checkout
	get 'single-checkout-success', to: 'checkout#single_checkout_success'
	get 'single-checkout-pending', to: 'checkout#single_checkout_pending'
	get 'single-checkout-cancelled', to: 'checkout#single_checkout_cancelled'

	get 'cart-checkout-success', to: 'checkout#cart_checkout_success'
	get 'cart-checkout-pending', to: 'checkout#cart_checkout_pending'
	get 'cart-checkout-cancelled', to: 'checkout#cart_checkout_cancelled'

	# API
	scope module: 'api' do
		scope '1', module: 'v1' do
			get 'user/favourites' => 'favourites#index'

			# Cart
			get 'user/products_in_cart', to: 'cart#get_products_in_cart', :as => :product_in_cart
			post 'user/checkout/:product_id', to: 'cart#add_product_to_cart', :as => :add_product_to_cart
			put 'user/checkout_row/:product_row_id', to: 'cart#edit_checkout_product_row', :as => :edit_checkout_row
			delete 'user/cart/:product_id', to: 'cart#remove_cart_product_row', :as => :remove_cart_product_row

			# Favourites
			post 'user/favourites/:product_id', to: 'favourites#create', :as => :add_product_to_favourites
			delete 'user/favourites/:product_id', to: 'favourites#destroy', :as => :remove_product_from_favourites

			post '/chat_response' => 'chat#dialog_flow_response'
		end
	end

	# error pages
	%w( 404 422 500 503 ).each do |code|
		get code, :to => 'errors#show', :code => code
	end


end

app/views/layouts/_contact_form.html.erb
<div class="contact-form">
  <div class="contact-form-inner">

    <i class="fa fa-times close-contact-form" aria-hidden="true"></i>

    <%= form_tag('/contact_email', :method => 'POST', :class => 'contact') do |f| %>
      <%= invisible_captcha %>
      <h5>hola@lazlo.la</h5>

      <input type="text" name="lazlo_name" placeholder="Nombre" required/>

      <input type="email" name="lazlo_email" placeholder="E-mail" required/>

      <textarea name="lazlo_message" placeholder="Consulta"></textarea>

      <%= submit_tag('ENVIAR', :class => 'smooth-transition yellow-button') %>
      </div>
    <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Start Footer -->
<footer class="footer">
  <div class="grilla">

    <div class="footer-block ">
      <h6>INSCRIBITE A NUESTRO NEWSLETTER</h6>

      <form class="newsletter-footer-form" url="<%= add_to_newsletter_url %>">
        <input type="email" name="email" class="newsletter-email" placeholder="Ingresa tú email">
        <button class="transparent-with-hover-yellow">ENVIAR</button>
      </form>

      <div class="social-icons">
        <a target="_blank" href="https://www.facebook.com/lazlo.design">
          <img src="<%= image_url('icons/facebook-icon-yellow.svg') %>">
        </a>

        <a target="_blank" href="https://www.instagram.com/lazlo.la/">
          <img src="<%= image_url('icons/instagram-icon-yellow.svg') %>">
        </a>

        <a target="_blank" href="https://pinterest.com/lazlola/">
          <img src="<%= image_url('icons/pinterest-icon-yellow.svg') %>">
        </a>

      </div>
    </div>

    <div class="footer-block">

      <h6>
        SEGUINOS EN INSTAGRAM
        <a href="https://www.instagram.com/<%= @instagram_username %>" target="_blank">
          @<%= @instagram_username %>
        </a>
      </h6>

      <% if @instagram_images.present? %>
        <div class="instagram-fotos">
          <% @instagram_images.each_with_index do |media_item, i| %>
            <a href="<%= media_item.link %>" target="_blank">
              <img src="<%= media_item.images.thumbnail.url %>">
            </a>
          <% end %>
        </div>
      <% end %>

    </div>

    <div class="footer-block">
      <h6>CONTACTO</h6>

      <div class="contact">
        <a href="tel:+5491158620355">
          <i class="fa fa-whatsapp" aria-hidden="true"></i>
          +54 911 5862 0355
        </a>
        <!--
         /
        <a href="tel:+541135555555">+54 11 3555 5555</a>
        -->
        <address alt="hola@lazlo.la">hola@lazlo.la</address>

      </div>


    </div>


  </div>
</footer>
<!-- End Footer-->


<!-- Dialog Flow -->
<!--<div class="chat-widget">-->

<!--  <div class="chat-button fast-transition">-->
<!--    <img class="fast-transition chat-balloon-icon">-->
<!--      <use xlink:href="<%#= image_url('sprite.img') %>#chat-icon"/>-->
<!--    </img>-->
<!--    <img class="fast-transition chat-cross-icon">-->
<!--      <use xlink:href="<%#= image_url('sprite.img') %>#close-cross-black"/>-->
<!--    </img>-->
<!--  </div>-->

<!--  <iframe class="chat-iframe display-on-chat fast-transition" src="https://console.dialogflow.com/api-client/demo/embedded/767b0398-573b-4573-bd3c-bf8f44907226"></iframe>-->

<!--  <div class="iframe-header display-on-chat fast-transition">-->

<!--    <div class="top-header">-->
<!--      <div class="logo-container circle-border-radious">-->
<!--        <img>-->
<!--          <use xlink:href="<%#= image_url('sprite.img') %>#lazlo-logo-white"/>-->
<!--        </img>-->
<!--      </div>-->
<!--      <h3>Bienvenido a Lazlo!</h3>-->

<!--    </div>-->

<!--    <div class="bottom-header">-->
<!--      Contame, en qué te podemos ayudar?-->
<!--    </div>-->
<!--  </div>-->

<!--</div>-->
<!-- End Dialog Flow -->




<div class="shadow-layer"></div>

</body>
</html>

app/views/layouts/_header.html.erb
<header class="nav-down">

  <!-- Notifications -->
  <div class="notification-bar notice">
    <p></p>
  </div>

  <div class="notification-bar alert">
    <p></p>
  </div>

  <script>
      <% if notice.present? %>
      showSuccessfulNotification('<%= notice %>');
      <% elsif alert.present? %>
      showFailedNotification('<%= alert %>');
      <% end %>
  </script>
  <!-- END Notifications -->


  <nav class="grilla">
    <div class="left-container">

      <a class="logo menu-button" href="<%= root_path %>">
        <img src="<%= image_url('logos/lazlo-logotipo.svg') %>">
      </a>

      <a class="menu-button products-menu-button <%= @current_section == 'products' ? 'current-section' : '' %>">
        <h2 class="expandable">
          PRODUCTOS
          <img src="<%= image_url('icons/menu-arrow-icon.svg') %>">
        </h2>
        <span class="smooth-transition"></span>
      </a>

      <a class="menu-button <%= @current_section == 'featured' ? 'current-section' : '' %>" href="<%= featured_path %>">
        <h2>DESTACADOS</h2>
        <span class="smooth-transition"></span>
      </a>

    </div>

    <div class="right-container">


      <a class="social-icons with-hover" target="_blank" href="https://www.facebook.com/lazlo.design">
        <span>
          <img class="header-icon" src="<%= image_url('icons/facebook-icon.svg') %>">
          <img class="hovered" src="<%= image_url('icons/facebook-icon-yellow.svg') %>">
        </span>
      </a>

      <a class="social-icons with-hover" target="_blank" href="https://www.instagram.com/lazlo.la/">
        <span>
          <img class="header-icon" src="<%= image_url('icons/instagram-icon.svg') %>">
          <img class="hovered" src="<%= image_url('icons/instagram-icon-yellow.svg') %>">
        </span>
      </a>

      <a class="social-icons with-hover" target="_blank" href="https://pinterest.com/lazlola/">
        <span>
          <img class="header-icon" src="<%= image_url('icons/pinterest-icon.svg') %>">
          <img class="hovered" src="<%= image_url('icons/pinterest-icon-yellow.svg') %>">
        </span>
      </a>

      <a class="social-icons with-hover contact-form-button">
        <span>
          <img class="header-icon" src="<%= image_url('icons/email-icon.svg') %>">
          <img class="hovered" src="<%= image_url('icons/email-icon-yellow.svg') %>">
        </span>
      </a>


      <a class="header-user-name" href="<%= user_signed_in? ? profile_url : new_user_session_path %>">
        <%= user_signed_in? ? current_user.email : 'iniciar sesión' %>
      </a>

      <a class="header-user-icon" href="<%= user_signed_in? ? profile_url : new_user_session_path %>">
        <i class="fa fa-user" aria-hidden="true"></i>
      </a>


      <a class="cart-button <%= user_signed_in? ? ' logged-cart-button' : '' %><%= @action == 'profile' ? '' : ' displayable' %> "
         href="<%= user_signed_in? ? checkout_path : new_user_session_path %>">
        <i class="fa fa-shopping-cart smooth-transition" aria-hidden="true"></i>
        <% if user_signed_in? and current_user.cart_count.present? %>
          <span class="notification-number"><%= current_user.cart_count %></span>
        <% end %>
      </a>
      <a class="responsive-menu with-hover">
        <span>
          <img class="header-icon" src="<%= image_url('icons/menu-responsive-icon.svg') %>">
        </span>
      </a>

    </div>

  </nav>

  <!-- Start Products menu -->
  <%= render :partial => 'layouts/products_menu' %>
  <!-- End Products menu -->

</header>


<% if @action != 'profile' %>
  <!-- Start Sidebar cart -->
  <%= render :partial => 'users/cart/sidebar_cart' %>
  <!-- End Sidebar cart -->
<% end %>

app/views/layouts/_products_menu.html.erb
<% if @page_categories.present? %>
    <div class="header-sub-menu products-sub-menu">
      <div class="grilla">


        <% @page_categories.each_with_index do |category| %>
            <div class="block">
              <div class="inner-block">
                <h3>
                  <a href="<%= category_path category %>">
                    <%= category.name %>
                  </a>
                </h3>
                <% category.products.limit(4).each do |product| %>
                    <a class="sub-category" href="<%= product_path product %>"><%= product.name %></a>
                <% end %>
                <% if category.products.count > 4 %>
                    <a class="see-more" href="<%= category_path category %>">
                      ver mas
                    </a>
                <% end %>
              </div>
            </div>
        <% end %>


      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @og_title.present? ? @og_title : 'Lazlo || Productos de Diseño' %></title>
  <meta name="keywords" content="mesa, ratona, auxiliar, de comedor, mesita, marmol, hierro, lampara, perchero, decoración, muebles, interiores, living, comedor, desayunador, consola, dresuar"/>
  <meta name="description"
        content="<%= @og_description.present? ? @og_description : 'Tienda online de productos de diseño. Creamos, desarrollamos y fabricamos objetos de decoración. Muebles, mesas, iluminación, deco, sillas y más.' %>"/>
  <meta name="canonical" content="http://lazlo.la"/>
  <meta name="robots" content="INDEX, FOLLOW"/>
  <meta name="author" content="amalgama.co"/>
  <meta name="viewport" content="width=1100, user-scalable=yes"/>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta http-equiv="Content-Language" content="ES"/>
  <link rel="alternate" hreflang="es" href="<%= @current_url || 'https://lazlo.la/' %>"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>


  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=10">

  <meta property="fb:app_id" content="1708824779437109"/>
  <meta property="og:url" content="<%= @current_url %>"/>
  <meta property="og:title" content="<%= @og_title.present? ? @og_title : 'Lazlo - Productos de Diseño' %>"/>
  <meta property="og:description" content="<%= @og_description.present? ? @og_description : 'Tienda online de productos de diseño. Creamos, desarrollamos y fabricamos objetos de decoración. Muebles, mesas, iluminación, deco, sillas y más.' %>"/>
  <meta property="og:image" content="<%= @og_image.present? ? @og_image : image_path('logos/lazlo-icon-100.png') %>"/>

  <meta name="HandheldFriendly" content="true"/>
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
  <meta name="apple-mobile-web-app-title" content="Lazlo">
  <meta name="viewport" content="initial-scale=1 maximum-scale=1 user-scalable=0 minimal-ui"/>

  <link rel="shortcut icon" href="<%= image_path('logos/lazlo-icon-40.png') %>">
  <link rel="icon" href="<%= image_path('logos/lazlo-icon-40.png') %>" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/fontawesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  <!-- Pinterest -->
  <meta name="p:domain_verify" content="6bb8bd20eb0d7f58bee98cf0410d6db3"/>

  <!-- Apple Icons -->
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <link rel="shortcut icon" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>" type="image/x-icon"/>
  <link rel="apple-touch-icon" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>
  <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path('logos/lazlo-icon-bg-100.png') %>"/>


  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Google Tag Manager -->
  <script>(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			 'gtm.start':
				  new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			 j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
  })(window, document, 'script', 'dataLayer', 'GTM-TVQGR3X');</script>
  <!-- End Google Tag Manager -->

</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TVQGR3X"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->

<%= yield %>

<!-- Start Contact Form -->
<%= render :partial => 'layouts/contact_form' %>
<!-- End Contact Form -->

<audio id="audio-up" src="<%= audio_url('audio-up.mp3') %>" preload="auto"></audio>
</body>
</html>